/*
npm run seed:photos

Needs VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local.
Safe to run more than once: it first removes the seed users' old photos.

Generated by AI
*/
import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const FOLDER = "supabase/seed-images";
const BUCKET = "safety-photos";

// Same users as seed.sql
const SEED_USERS = [
  "tom.nook@example.com",
  "mario@example.com",
  "isaac.clarke@example.com",
  "wario@example.com",
];

// Each photo goes on that worker's most recent submission at that site.
// A submission can have more than one photo.
const PHOTOS = [
  {
    email: "mario@example.com",
    site: "Pallet Town",
    file: "frayed-hi-vis.png",
  },
  {
    email: "mario@example.com",
    site: "Rapture",
    file: "unsafe-ledge-no-railing.png",
  },
  {
    email: "tom.nook@example.com",
    site: "Pallet Town",
    file: "frayed-cord.png",
  },
  { email: "wario@example.com", site: "Vault 101", file: "helmet-cracked.png" },
  {
    email: "wario@example.com",
    site: "Vault 101",
    file: "missing-eye-protection.png",
  },
  {
    email: "wario@example.com",
    site: "Pallet Town",
    file: "no-inspection-tag-scaffold.png",
  },
];

// The only types the safety-photos bucket accepts
const MIME_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

const url = process.env.VITE_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !serviceKey) {
  console.error(
    "Add VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to .env.local",
  );
  process.exit(1);
}

const supabase = createClient(url, serviceKey);
const storage = supabase.storage.from(BUCKET);

const { data: userList, error: usersError } =
  await supabase.auth.admin.listUsers();
if (usersError) throw usersError;

function findUserId(email: string) {
  const user = userList.users.find((u) => u.email === email);
  if (!user) {
    throw new Error(
      `No user ${email}. Create it in the dashboard and run seed.sql first.`,
    );
  }
  return user.id;
}

// 1. Remove the seed users' old photos: the files at {worker_id}/{submission_id}/... and their rows.
for (const email of SEED_USERS) {
  const workerId = findUserId(email);

  const { data: folders } = await storage.list(workerId);
  for (const folder of folders ?? []) {
    const { data: files } = await storage.list(`${workerId}/${folder.name}`);
    const paths = (files ?? []).map(
      (f) => `${workerId}/${folder.name}/${f.name}`,
    );
    if (paths.length > 0) {
      const { error } = await storage.remove(paths);
      if (error) throw error;
    }
  }

  const { error } = await supabase
    .from("submission_photos")
    .delete()
    .like("storage_path", `${workerId}/%`);
  if (error) throw error;
}

// 2. Upload each photo and record it on its submission.
for (const photo of PHOTOS) {
  const extension = photo.file.split(".").pop()!.toLowerCase();
  const mimeType = MIME_TYPES[extension];
  if (!mimeType)
    throw new Error(`${photo.file}: use a .jpg, .png or .webp file`);

  const workerId = findUserId(photo.email);

  const { data: site, error: siteError } = await supabase
    .from("sites")
    .select("id")
    .eq("name", photo.site)
    .single();
  if (siteError)
    throw new Error(`No site named ${photo.site}. Run seed.sql first.`);

  const { data: submission, error: submissionError } = await supabase
    .from("submissions")
    .select("id")
    .eq("worker_id", workerId)
    .eq("site_id", site.id)
    .order("work_date", { ascending: false })
    .limit(1)
    .single();
  if (submissionError) {
    throw new Error(
      `No submission by ${photo.email} at ${photo.site}. Run seed.sql first.`,
    );
  }

  const bytes = readFileSync(`${FOLDER}/${photo.file}`);
  const path = `${workerId}/${submission.id}/${crypto.randomUUID()}.${extension}`;

  const { error: uploadError } = await storage.upload(path, bytes, {
    contentType: mimeType,
  });
  if (uploadError) throw new Error(`${photo.file}: ${uploadError.message}`);

  const { error: rowError } = await supabase.from("submission_photos").insert({
    submission_id: submission.id,
    storage_path: path,
    mime_type: mimeType,
    size_bytes: bytes.length,
  });
  if (rowError) throw rowError;

  console.log(`${photo.file} -> ${photo.email} at ${photo.site}`);
}

console.log(`Done: ${PHOTOS.length} photos uploaded.`);
